-- etcd join date
\set join_date '2018-12-11'
-- Cilium join date
-- \set join_date '2021-10-13'

-- Before join
select count(distinct e.id) as "Contributions before join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at < :'join_date';
select count(distinct e.id) as "Affiliated contributions before join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at < :'join_date' and aa.company_name is not null and lower(aa.company_name) != 'independent';
select count(distinct e.id) as "Unaffiliated contributions before join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at < :'join_date' and aa.company_name is null;
select count(distinct e.id) as "Individual contributions before join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at < :'join_date' and lower(aa.company_name) = 'independent';
-- After join
select count(distinct e.id) as "Contributions after join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at >= :'join_date';
select count(distinct e.id) as "Affiliated contributions after join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at >= :'join_date' and aa.company_name is not null and lower(aa.company_name) != 'independent';
select count(distinct e.id) as "Unaffiliated contributions after join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at >= :'join_date' and aa.company_name is null;
select count(distinct e.id) as "Individual contributions after join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at >= :'join_date' and lower(aa.company_name) = 'independent';
-- All time
select count(distinct e.id) as "All time contributions" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent');
select count(distinct e.id) as "All time affiliated contributions" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and aa.company_name is not null and lower(aa.company_name) != 'independent';
select count(distinct e.id) as "All time unaffiliated contributions" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and aa.company_name is null;
select count(distinct e.id) as "All time individual contributions" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and lower(aa.company_name) = 'independent';
-- New after join
select count(distinct e.id) as "New contributions after join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at >= :'join_date' and e.actor_id not in (select e.actor_id from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at < :'join_date');
select count(distinct e.id) as "New affiliated contributions after join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at >= :'join_date' and aa.company_name is not null and lower(aa.company_name) != 'independent' and e.actor_id not in (select e.actor_id from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at < :'join_date');
select count(distinct e.id) as "New unaffiliated contributions after join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at >= :'join_date' and aa.company_name is null and e.actor_id not in (select e.actor_id from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at < :'join_date');
select count(distinct e.id) as "New individual contributions after join" from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at >= :'join_date' and lower(aa.company_name) = 'independent' and e.actor_id not in (select e.actor_id from gha_events e left join gha_actors_affiliations aa on aa.actor_id = e.actor_id and aa.dt_from <= e.created_at and aa.dt_to > e.created_at where e.type in ('PushEvent', 'PullRequestEvent', 'IssuesEvent', 'PullRequestReviewEvent', 'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent') and e.created_at < :'join_date');
